using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;


namespace CBetApi.Models
{
    public class Country
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }

        public static readonly List<Country> countryList = new List<Country>
     {
            new Country{Id = 1 ,Name = "Afghanistan", Code = "AF"},
            new Country{Id = 1 ,Name = "Albania", Code = "AL"},
            new Country{Id = 1 ,Name = "Algeria", Code = "DZ"},
           // new Country{Id = 1 ,Name = "American Samoa", Code = "AS"},
           // new Country{Id = 1 ,Name = "Andorra", Code = "AD"},
            new Country{Id = 1 ,Name = "Angola", Code = "AO"},
            //new Country{Id = 1 ,Name = "Anguilla", Code = "AI"},
            //new Country{Id = 1 ,Name = "Antarctica", Code = "AQ"},
            new Country{Id = 1 ,Name = "Antigua and Barbuda", Code = "AG"},
            new Country{Id = 1 ,Name = "Argentina", Code = "AR"},
            new Country{Id = 1 ,Name = "Armenia", Code = "AM"},
       //     new Country{Id = 1 ,Name = "Aruba", Code = "AW"},
            new Country{Id = 1 ,Name = "Australia", Code = "AU"},
            new Country{Id = 1 ,Name = "Austria", Code = "AT"},
            new Country{Id = 1 ,Name = "Azerbaijan", Code = "AZ"},
            new Country{Id = 1 ,Name = "Bahamas", Code = "BS"},
            new Country{Id = 1 ,Name = "Bahrain", Code = "BH"},
            new Country{Id = 1 ,Name = "Bangladesh", Code = "BD"},
            new Country{Id = 1 ,Name = "Barbados", Code = "BB"},
            new Country{Id = 1 ,Name = "Belarus", Code = "BY"},
            new Country{Id = 1 ,Name = "Belgium", Code = "BE"},
            new Country{Id = 1 ,Name = "Belize", Code = "BZ"},
            new Country{Id = 1 ,Name = "Benin", Code = "BJ"},
          //  new Country{Id = 1 ,Name = "Bermuda", Code = "BM"},
            new Country{Id = 1 ,Name = "Bhutan", Code = "BT"},
            new Country{Id = 1 ,Name = "Bolivia", Code = "BO"},
           // new Country{Id = 1 ,Name = "Bonaire, Sint Eustatius and Saba", Code = "BQ"},
            new Country{Id = 1 ,Name = "Bosnia and Herzegovina", Code = "BA"},
            new Country{Id = 1 ,Name = "Botswana", Code = "BW"},
          //  new Country{Id = 1 ,Name = "Bouvet Island", Code = "BV"},
            new Country{Id = 1 ,Name = "Brazil", Code = "BR"},
           // new Country{Id = 1 ,Name = "British Indian Ocean Territory", Code = "IO"},
            new Country{Id = 1 ,Name = "Brunei", Code = "BN"},
            new Country{Id = 1 ,Name = "Bulgaria", Code = "BG"},
            new Country{Id = 1 ,Name = "Burkina Faso", Code = "BF"},
            new Country{Id = 1 ,Name = "Burundi", Code = "BI"},
            new Country{Id = 1 ,Name = "Cabo Verde", Code = "CV"},
            new Country{Id = 1 ,Name = "Cambodia", Code = "KH"},
            new Country{Id = 1 ,Name = "Cameroon", Code = "CM"},
            new Country{Id = 1 ,Name = "Canada", Code = "CA"},
            new Country{Id = 1 ,Name = "Cayman Islands", Code = "KY"},
            new Country{Id = 1 ,Name = "Central African Republic", Code = "CF"},
            new Country{Id = 1 ,Name = "Chad", Code = "TD"},
            new Country{Id = 1 ,Name = "Chile", Code = "CL"},
            new Country{Id = 1 ,Name = "China", Code = "CN"},
           // new Country{Id = 1 ,Name = "Christmas Island", Code = "CX"},
            //new Country{Id = 1 ,Name = "Cocos {Keeling} Islands", Code = "CC"},
            new Country{Id = 1 ,Name = "Colombia", Code = "CO"},
            new Country{Id = 1 ,Name = "Comoros", Code = "KM"},
            new Country{Id = 1 ,Name = "Congo (Brazzaville)", Code = "CG"},
            new Country{Id = 1 ,Name = "Congo (Kinshasa)", Code = "CD"},
          //  new Country{Id = 1 ,Name = "Cook Islands", Code = "CK"},
            new Country{Id = 1 ,Name = "Costa Rica", Code = "CR"},
            new Country{Id = 1 ,Name = "Cote d'Ivoire", Code = "CI"},
            new Country{Id = 1 ,Name = "Croatia", Code = "HR"},
            new Country{Id = 1 ,Name = "Cuba", Code = "CU"},
           // new Country{Id = 1 ,Name = "Curaçao", Code = "CW"},
            new Country{Id = 1 ,Name = "Cyprus", Code = "CY"},
            new Country{Id = 1 ,Name = "Czechia", Code = "CZ"},
            new Country{Id = 1 ,Name = "Denmark", Code = "DK"},
            new Country{Id = 1 ,Name = "Djibouti", Code = "DJ"},
            new Country{Id = 1 ,Name = "Dominica", Code = "DM"},
            new Country{Id = 1 ,Name = "Dominican Republic", Code = "DO"},
            new Country{Id = 1 ,Name = "Ecuador", Code = "EC"},
            new Country{Id = 1 ,Name = "Egypt", Code = "EG"},
            new Country{Id = 1 ,Name = "El Salvador", Code = "SV"},
            new Country{Id = 1 ,Name = "Equatorial Guinea", Code = "GQ"},
            new Country{Id = 1 ,Name = "Eritrea", Code = "ER"},
            new Country{Id = 1 ,Name = "Estonia", Code = "EE"},
            new Country{Id = 1 ,Name = "Eswatini", Code = "SZ"},
            new Country{Id = 1 ,Name = "Ethiopia", Code = "ET"},
           // new Country{Id = 1 ,Name = "Falkland Islands {Malvinas}", Code = "FK"},
            //new Country{Id = 1 ,Name = "Faroe Islands", Code = "FO"},
            new Country{Id = 1 ,Name = "Fiji", Code = "FJ"},
            new Country{Id = 1 ,Name = "Finland", Code = "FI"},
            new Country{Id = 1 ,Name = "France", Code = "FR"},
         //  new Country{Id = 1 ,Name = "French Guiana", Code = "GF"},
          //  new Country{Id = 1 ,Name = "French Polynesia", Code = "PF"},
            //new Country{Id = 1 ,Name = "French Southern Territories", Code = "TF"},
            new Country{Id = 1 ,Name = "Gabon", Code = "GA"},
            new Country{Id = 1 ,Name = "Gambia", Code = "GM"},
            new Country{Id = 1 ,Name = "Georgia", Code = "GE"},
            new Country{Id = 1 ,Name = "Germany", Code = "DE"},
            new Country{Id = 1 ,Name = "Ghana", Code = "GH"},
          //  new Country{Id = 1 ,Name = "Gibraltar", Code = "GI"},
            new Country{Id = 1 ,Name = "Greece", Code = "GR"},
            //new Country{Id = 1 ,Name = "Greenland", Code = "GL"},
            new Country{Id = 1 ,Name = "Grenada", Code = "GD"},
         //   new Country{Id = 1 ,Name = "Guadeloupe", Code = "GP"},
           // new Country{Id = 1 ,Name = "Guam", Code = "GU"},
            new Country{Id = 1 ,Name = "Guatemala", Code = "GT"},
           // new Country{Id = 1 ,Name = "Guernsey", Code = "GG"},
            new Country{Id = 1 ,Name = "Guinea", Code = "GN"},
            new Country{Id = 1 ,Name = "Guinea-Bissau", Code = "GW"},
            new Country{Id = 1 ,Name = "Guyana", Code = "GY"},
            new Country{Id = 1 ,Name = "Haiti", Code = "HT"},
           // new Country{Id = 1 ,Name = "Heard Island and McDonald Islands", Code = "HM"},
          //  new Country{Id = 1 ,Name = "Holy See", Code = "VA"},
            new Country{Id = 1 ,Name = "Honduras", Code = "HN"},
         //   new Country{Id = 1 ,Name = "Hong Kong", Code = "HK"},
            new Country{Id = 1 ,Name = "Hungary", Code = "HU"},
            new Country{Id = 1 ,Name = "Iceland", Code = "IS"},
            new Country{Id = 1 ,Name = "India", Code = "IN"},
            new Country{Id = 1 ,Name = "Indonesia", Code = "ID"},
            new Country{Id = 1 ,Name = "Iran", Code = "IR"},
            new Country{Id = 1 ,Name = "Iraq", Code = "IQ"},
            new Country{Id = 1 ,Name = "Ireland", Code = "IE"},
         //   new Country{Id = 1 ,Name = "Isle of Man", Code = "IM"},
            new Country{Id = 1 ,Name = "Israel", Code = "IL"},
            new Country{Id = 1 ,Name = "Italy", Code = "IT"},
            new Country{Id = 1 ,Name = "Jamaica", Code = "JM"},
            new Country{Id = 1 ,Name = "Japan", Code = "JP"},
           // new Country{Id = 1 ,Name = "Jersey", Code = "JE"},
            new Country{Id = 1 ,Name = "Jordan", Code = "JO"},
            new Country{Id = 1 ,Name = "Kazakhstan", Code = "KZ"},
            new Country{Id = 1 ,Name = "Kenya", Code = "KE"},
          //  new Country{Id = 1 ,Name = "Kiribati", Code = "KI"},
           // new Country{Id = 1 ,Name = "Korea, Democratic People's Republic of", Code = "KP"},
            new Country{Id = 1 ,Name = "Korea, South", Code = "KR"},
            new Country{Id = 1 ,Name = "Kosovo", Code = "KS"},
            new Country{Id = 1 ,Name = "Kuwait", Code = "KW"},
            new Country{Id = 1 ,Name = "Kyrgyzstan", Code = "KG"},
            new Country{Id = 1 ,Name = "Laos", Code = "LA"},
            new Country{Id = 1 ,Name = "Latvia", Code = "LV"},
            new Country{Id = 1 ,Name = "Lebanon", Code = "LB"},
            new Country{Id = 1 ,Name = "Lesotho", Code = "LS"},
            new Country{Id = 1 ,Name = "Liberia", Code = "LR"},
            new Country{Id = 1 ,Name = "Libya", Code = "LY"},
            new Country{Id = 1 ,Name = "Liechtenstein", Code = "LI"},
            new Country{Id = 1 ,Name = "Lithuania", Code = "LT"},
            new Country{Id = 1 ,Name = "Luxembourg", Code = "LU"},
           // new Country{Id = 1 ,Name = "Macao", Code = "MO"},
            new Country{Id = 1 ,Name = "Madagascar", Code = "MG"},
            new Country{Id = 1 ,Name = "Malawi", Code = "MW"},
            new Country{Id = 1 ,Name = "Malaysia", Code = "MY"},
            new Country{Id = 1 ,Name = "Maldives", Code = "MV"},
            new Country{Id = 1 ,Name = "Mali", Code = "ML"},
            new Country{Id = 1 ,Name = "Malta", Code = "MT"},
            new Country{Id = 1 ,Name = "Marshall Islands", Code = "MH"},
           // new Country{Id = 1 ,Name = "Martinique", Code = "MQ"},
            new Country{Id = 1 ,Name = "Mauritania", Code = "MR"},
            new Country{Id = 1 ,Name = "Mauritius", Code = "MU"},
          //  new Country{Id = 1 ,Name = "Mayotte", Code = "YT"},
            new Country{Id = 1 ,Name = "Mexico", Code = "MX"},
            new Country{Id = 1 ,Name = "Micronesia", Code = "FM"},
            new Country{Id = 1 ,Name = "Moldova", Code = "MD"},
            new Country{Id = 1 ,Name = "Monaco", Code = "MC"},
            new Country{Id = 1 ,Name = "Mongolia", Code = "MN"},
            new Country{Id = 1 ,Name = "Montenegro", Code = "ME"},
          // new Country{Id = 1 ,Name = "Montserrat", Code = "MS"},
            new Country{Id = 1 ,Name = "Morocco", Code = "MA"},
            new Country{Id = 1 ,Name = "Mozambique", Code = "MZ"},
            new Country{Id = 1 ,Name = "Burma", Code = "MM"},
            new Country{Id = 1 ,Name = "Namibia", Code = "NA"},
      //      new Country{Id = 1 ,Name = "Nauru", Code = "NR"},
            new Country{Id = 1 ,Name = "Nepal", Code = "NP"},
            new Country{Id = 1 ,Name = "Netherlands", Code = "NL"},
            new Country{Id = 1 ,Name = "New Caledonia", Code = "NC"},
            new Country{Id = 1 ,Name = "New Zealand", Code = "NZ"},
            new Country{Id = 1 ,Name = "Nicaragua", Code = "NI"},
            new Country{Id = 1 ,Name = "Niger", Code = "NE"},
            new Country{Id = 1 ,Name = "Nigeria", Code = "NG"},
           // new Country{Id = 1 ,Name = "Niue", Code = "NU"},
           // new Country{Id = 1 ,Name = "Norfolk Island", Code = "NF"},
           // new Country{Id = 1 ,Name = "Northern Mariana Islands", Code = "MP"},
            new Country{Id = 1 ,Name = "North Macedonia", Code = "MK"},
            new Country{Id = 1 ,Name = "Norway", Code = "NO"},
            new Country{Id = 1 ,Name = "Oman", Code = "OM"},
            new Country{Id = 1 ,Name = "Pakistan", Code = "PK"},
         //   new Country{Id = 1 ,Name = "Palau", Code = "PW"},
          //  new Country{Id = 1 ,Name = "Palestine, State of", Code = "PS"},
            new Country{Id = 1 ,Name = "Panama", Code = "PA"},
            new Country{Id = 1 ,Name = "Papua New Guinea", Code = "PG"},
            new Country{Id = 1 ,Name = "Paraguay", Code = "PY"},
            new Country{Id = 1 ,Name = "Peru", Code = "PE"},
            new Country{Id = 1 ,Name = "Philippines", Code = "PH"},
            new Country{Id = 1 ,Name = "Pitcairn", Code = "PN"},
            new Country{Id = 1 ,Name = "Poland", Code = "PL"},
            new Country{Id = 1 ,Name = "Portugal", Code = "PT"},
          //  new Country{Id = 1 ,Name = "Puerto Rico", Code = "PR"},
            new Country{Id = 1 ,Name = "Qatar", Code = "QA"},
            //new Country{Id = 1 ,Name = "Réunion", Code = "RE"},
            new Country{Id = 1 ,Name = "Romania", Code = "RO"},
            new Country{Id = 1 ,Name = "Russia", Code = "RU"},
            new Country{Id = 1 ,Name = "Rwanda", Code = "RW"},
          //  new Country{Id = 1 ,Name = "Saint Barthélemy", Code = "BL"},
           // new Country{Id = 1 ,Name = "Saint Helena, Ascension and Tristan da Cunha", Code = "SH"},
            new Country{Id = 1 ,Name = "Saint Kitts and Nevis", Code = "KN"},
            new Country{Id = 1 ,Name = "Saint Lucia", Code = "LC"},
            //new Country{Id = 1 ,Name = "Saint Martin {French part}", Code = "MF"},
            //new Country{Id = 1 ,Name = "Saint Pierre and Miquelon", Code = "PM"},
            new Country{Id = 1 ,Name = "Saint Vincent and the Grenadines", Code = "VC"},
            new Country{Id = 1 ,Name = "Samoa", Code = "WS"},
            new Country{Id = 1 ,Name = "San Marino", Code = "SM"},
            new Country{Id = 1 ,Name = "Sao Tome and Principe", Code = "ST"},
            new Country{Id = 1 ,Name = "Saudi Arabia", Code = "SA"},
            new Country{Id = 1 ,Name = "Senegal", Code = "SN"},
            new Country{Id = 1 ,Name = "Serbia", Code = "RS"},
            new Country{Id = 1 ,Name = "Seychelles", Code = "SC"},
            new Country{Id = 1 ,Name = "Sierra Leone", Code = "SL"},
            new Country{Id = 1 ,Name = "Singapore", Code = "SG"},
          //  new Country{Id = 1 ,Name = "Sint Maarten {Dutch part}", Code = "SX"},
            new Country{Id = 1 ,Name = "Slovakia", Code = "SK"},
            new Country{Id = 1 ,Name = "Slovenia", Code = "SI"},
            new Country{Id = 1 ,Name = "Solomon Islands", Code = "SB"},
            new Country{Id = 1 ,Name = "Somalia", Code = "SO"},
            new Country{Id = 1 ,Name = "South Africa", Code = "ZA"},
         //   new Country{Id = 1 ,Name = "South Georgia and the South Sandwich Islands", Code = "GS"},
            new Country{Id = 1 ,Name = "South Sudan", Code = "SS"},
            new Country{Id = 1 ,Name = "Spain", Code = "ES"},
            new Country{Id = 1 ,Name = "Sri Lanka", Code = "LK"},
            new Country{Id = 1 ,Name = "Sudan", Code = "SD"},
            new Country{Id = 1 ,Name = "Suriname", Code = "SR"},
          //  new Country{Id = 1 ,Name = "Svalbard and Jan Mayen", Code = "SJ"},
            new Country{Id = 1 ,Name = "Sweden", Code = "SE"},
            new Country{Id = 1 ,Name = "Switzerland", Code = "CH"},
            new Country{Id = 1 ,Name = "Syria", Code = "SY"},
            new Country{Id = 1 ,Name = "Taiwan", Code = "TW"},
            new Country{Id = 1 ,Name = "Tajikistan", Code = "TJ"},
            new Country{Id = 1 ,Name = "Tanzania", Code = "TZ"},
            new Country{Id = 1 ,Name = "Thailand", Code = "TH"},
            new Country{Id = 1 ,Name = "Timor-Leste", Code = "TL"},
            new Country{Id = 1 ,Name = "Togo", Code = "TG"},
          //  new Country{Id = 1 ,Name = "Tokelau", Code = "TK"},
           // new Country{Id = 1 ,Name = "Tonga", Code = "TO"},
            new Country{Id = 1 ,Name = "Trinidad and Tobago", Code = "TT"},
            new Country{Id = 1 ,Name = "Tunisia", Code = "TN"},
            new Country{Id = 1 ,Name = "Turkey", Code = "TR"},
      //      new Country{Id = 1 ,Name = "Turkmenistan", Code = "TM"},
       //     new Country{Id = 1 ,Name = "Turks and Caicos Islands", Code = "TC"},
         //   new Country{Id = 1 ,Name = "Tuvalu", Code = "TV"},
            new Country{Id = 1 ,Name = "Uganda", Code = "UG"},
            new Country{Id = 1 ,Name = "Ukraine", Code = "UA"},
            new Country{Id = 1 ,Name = "United Arab Emirates", Code = "AE"},
            new Country{Id = 1 ,Name = "United Kingdom", Code = "GB"},
            new Country{Id = 1 ,Name = "US", Code = "US"},
          //  new Country{Id = 1 ,Name = "United States Minor Outlying Islands", Code = "UM"},
            new Country{Id = 1 ,Name = "Uruguay", Code = "UY"},
            new Country{Id = 1 ,Name = "Uzbekistan", Code = "UZ"},
            new Country{Id = 1 ,Name = "Vanuatu", Code = "VU"},
            new Country{Id = 1 ,Name = "Venezuela", Code = "VE"},
            new Country{Id = 1 ,Name = "Vietnam", Code = "VN"},
          // new Country{Id = 1 ,Name = "Virgin Islands, British", Code = "VG"},
           // new Country{Id = 1 ,Name = "Virgin Islands, U.S.", Code = "VI"},
            //new Country{Id = 1 ,Name = "Wallis and Futuna", Code = "WF"},
            //new Country{Id = 1 ,Name = "Western Sahara", Code = "EH"},
            new Country{Id = 1 ,Name = "Yemen", Code = "YE"},
            new Country{Id = 1 ,Name = "Zambia", Code = "ZM"},
            new Country{Id = 1 ,Name = "Zimbabwe", Code = "ZW"},
          //  new Country{Id = 1 ,Name = "Åland Islands",Code =  "AX"},
            new Country{Id = 1,Name = "Global" , Code = "GL"}
        };
    }
}
