// <auto-generated />
using System;
using CBetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CBetApi.Migrations
{
    [DbContext(typeof(CBetApiDbContext))]
    [Migration("20210627182610_favorites")]
    partial class favorites
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CBetApi.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<float>("Coeficient")
                        .HasColumnType("real");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PayoutAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("CBetApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 11,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 12,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 13,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 14,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 15,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 28,
                            Code = "CV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 29,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 30,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 31,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 32,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CG",
                            Name = "Congo (Brazzaville)"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CD",
                            Name = "Congo (Kinshasa)"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Code = "CI",
                            Name = "Cote d'Ivoire"
                        },
                        new
                        {
                            Id = 43,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CZ",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 47,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 48,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 49,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 51,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Code = "SZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 58,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 75,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 82,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Code = "KR",
                            Name = "Korea, South"
                        },
                        new
                        {
                            Id = 90,
                            Code = "KS",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 91,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Code = "MM",
                            Name = "Burma"
                        },
                        new
                        {
                            Id = 120,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 122,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 123,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 124,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Code = "MK",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 133,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 134,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 135,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 136,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 137,
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 138,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 139,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 140,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 141,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 142,
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 143,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 144,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 145,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 146,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 147,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 148,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 150,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 151,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 153,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 154,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 155,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 156,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 157,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 158,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 159,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 160,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 161,
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 162,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 163,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 164,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 165,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 166,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 167,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 168,
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 169,
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 170,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 171,
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 172,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 173,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 174,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 175,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 176,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 177,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 178,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 179,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 180,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 181,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 182,
                            Code = "US",
                            Name = "US"
                        },
                        new
                        {
                            Id = 183,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 184,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 185,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 186,
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 187,
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 188,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 189,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 190,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = 191,
                            Code = "GL",
                            Name = "Global"
                        });
                });

            modelBuilder.Entity("CBetApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FavoritedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CBetApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ThirdParty")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CBetApi.Models.Bet", b =>
                {
                    b.HasOne("CBetApi.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
